### ISSUE TITLE
World Image bugs the app

### ISSUE THREAD

**Issue by maplepy** [AIP21/TrackerDecoderApp#2]
![image](https://user-images.githubusercontent.com/28269333/174780509-c13e826a-f3cd-4918-a307-156059e7b8d0.png)

When trying to load a world image, it just freezes the app and I can't do anything but restart the app

**Comment by AIP21** [comment]
Hmm... could you please send the log file? It should be located in the run directory in a folder called "logs" and is the newest file listed.

It might be that the app runs out of memory when loading the image, since it might be too large. It could also just be taking a really long time if it's a super large world image.

**Comment by maplepy** [comment]
[2022-06-23.log.txt](https://github.com/AIP21/TrackerDecoderApp/files/8969440/2022-06-23.log.txt)

Sure there it is, also I'm on Linux, doesn't know if that changes a thing and I used `OpenJDK Java 18`

Note: this happens with the 1.1 and 1.0.4 versions of the app

**Comment by maplepy** [comment]
I also face other issues when I try to see the data, when zooming it leaves a weird trace but I can't reproduce it anymore with the latest release

**Comment by AIP21** [comment]
Ok, so according to the log the image is successfully loaded, in 14 milliseconds. Given the really short loading time I'm assuming the image is a pretty small size, although I could be wrong there.
I haven't tested the app on Linux so I'm not sure if it's an issue with Linux. Most likely not though, since the image is being properly loaded.

Could you please try running it from a console window, as sometimes errors are printed in the console but aren't logged in the log file for some reason. To do that just open a console window and navigate to the run directory and enter "java -jar <name of .jar file> -debug" The -debug is important since it makes it print more information to the console.
Then just copy and paste the console output send it here. 

Sorry about the wall of text, I try to be as descriptive as possible.

**Comment by AIP21** [comment]
As for the issues with zooming, it was just a bug that I accidentally introduced in an update that for some reason caused issues with rendering. I fixed it with the latest release.

**Comment by maplepy** [comment]
![test](https://user-images.githubusercontent.com/28269333/175555548-d49ff279-9a43-490c-b19c-d08799e4bb1d.png)

This is the image and its size is `264.6 KiB (270,939 bytes)`

**Comment by maplepy** [comment]
#### Without debug mode

```
~/Github/mc_player_tracker ❯ java -jar TrackerDecoderApp-1.1.0-Full.Release.jar
   [INFO.1] <2022-06-24; 16:23:29.339> Player Tracker Decoder App v1.1.0-FR - LOG FILE
   [INFO.1] <2022-06-24; 16:23:29.780> Logger successfully initialized
   [INFO.1] <2022-06-24; 16:23:29.781> Initializing primary subsystems
   [INFO.1] <2022-06-24; 16:23:29.781> 1.1.0-FR, 0
   [INFO.1] <2022-06-24; 16:23:29.781> Light, 1
   [INFO.1] <2022-06-24; 16:23:29.781> 60, 2
   [INFO.1] <2022-06-24; 16:23:29.782> 0.5, 3
   [INFO.1] <2022-06-24; 16:23:29.782> true, 4
   [INFO.1] <2022-06-24; 16:23:29.782> 0, 5
   [INFO.1] <2022-06-24; 16:23:29.782> Line, 6
   [INFO.1] <2022-06-24; 16:23:29.782> 200, 7
   [INFO.1] <2022-06-24; 16:23:29.783> false, 8
   [INFO.1] <2022-06-24; 16:23:29.783> false, 9
   [INFO.1] <2022-06-24; 16:23:29.783> false, 10
   [INFO.1] <2022-06-24; 16:23:29.783> true, 11
   [INFO.1] <2022-06-24; 16:23:29.784> false, 12
   [INFO.1] <2022-06-24; 16:23:29.784> 1.0, 13
   [INFO.1] <2022-06-24; 16:23:29.784> Color, 14
   [INFO.1] <2022-06-24; 16:23:29.784> 1.0, 15
   [INFO.1] <2022-06-24; 16:23:29.784> 100, 16
   [INFO.1] <2022-06-24; 16:23:29.785> Successfully fetched and parsed settings from config file
   [INFO.1] <2022-06-24; 16:23:29.785> Successfully initialized settings subsystem
   [INFO.1] <2022-06-24; 16:23:29.785> Initializing decoder subsystem
   [INFO.1] <2022-06-24; 16:23:29.785> Successfully initialized decoder subsystem
   [INFO.1] <2022-06-24; 16:23:29.786> Initializing main display subsystem
   [INFO.1] <2022-06-24; 16:23:29.786> Successfully initialized main display subsystem
   [INFO.1] <2022-06-24; 16:23:29.786> Successfully initialized primary frame subsystem
   [INFO.1] <2022-06-24; 16:23:29.787> Successfully initialized all subsystems
   Exception in thread "Thread-1" java.lang.IllegalArgumentException: invalid range properties
	at java.desktop/javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:109)
	at java.desktop/javax.swing.JSlider.<init>(JSlider.java:293)
	at src.PlayerTrackerDecoder.lambda$LoadWorldImage$6(PlayerTrackerDecoder.java:325)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

#### With debug mode on

```
~/Github/mc_player_tracker ❯ java -jar TrackerDecoderApp-1.1.0-Full.Release.jar -debug
   [INFO.1] <2022-06-24; 16:25:35.924> Player Tracker Decoder App v1.1.0-FR - LOG FILE
   [INFO.0] <2022-06-24; 16:25:36.324> Initializing logger
   [WARNING] <2022-06-24; 16:25:36.327> DEBUG MODE IS ON, PERFORMANCE MAY BE LOWER
   [INFO.1] <2022-06-24; 16:25:36.328> Logger successfully initialized
   [INFO.1] <2022-06-24; 16:25:36.328> Initializing primary subsystems
   [INFO.0] <2022-06-24; 16:25:36.328> Initializing settings subsystem
   [INFO.0] <2022-06-24; 16:25:36.328> Fetching and parsing settings from config file
   [INFO.1] <2022-06-24; 16:25:36.328> 1.1.0-FR, 0
   [INFO.1] <2022-06-24; 16:25:36.329> Light, 1
   [INFO.1] <2022-06-24; 16:25:36.329> 60, 2
   [INFO.1] <2022-06-24; 16:25:36.329> 0.5, 3
   [INFO.1] <2022-06-24; 16:25:36.329> true, 4
   [INFO.1] <2022-06-24; 16:25:36.329> 0, 5
   [INFO.1] <2022-06-24; 16:25:36.329> Line, 6
   [INFO.1] <2022-06-24; 16:25:36.330> 200, 7
   [INFO.1] <2022-06-24; 16:25:36.330> false, 8
   [INFO.1] <2022-06-24; 16:25:36.330> false, 9
   [INFO.1] <2022-06-24; 16:25:36.330> false, 10
   [INFO.1] <2022-06-24; 16:25:36.330> true, 11
   [INFO.1] <2022-06-24; 16:25:36.330> false, 12
   [INFO.1] <2022-06-24; 16:25:36.330> 1.0, 13
   [INFO.1] <2022-06-24; 16:25:36.331> Color, 14
   [INFO.1] <2022-06-24; 16:25:36.331> 1.0, 15
   [INFO.1] <2022-06-24; 16:25:36.331> 100, 16
   [INFO.0] <2022-06-24; 16:25:36.331> Settings count: 16
   [INFO.1] <2022-06-24; 16:25:36.331> Successfully fetched and parsed settings from config file
   [INFO.1] <2022-06-24; 16:25:36.331> Successfully initialized settings subsystem
   [INFO.1] <2022-06-24; 16:25:36.331> Initializing decoder subsystem
   [INFO.1] <2022-06-24; 16:25:36.332> Successfully initialized decoder subsystem
   [INFO.0] <2022-06-24; 16:25:36.332> Loading resources
   [INFO.0] <2022-06-24; 16:25:36.332> Initializing primary frame subsystem
   [INFO.1] <2022-06-24; 16:25:36.332> Initializing main display subsystem
   [INFO.1] <2022-06-24; 16:25:36.332> Successfully initialized main display subsystem
   [INFO.1] <2022-06-24; 16:25:36.332> Successfully initialized primary frame subsystem
   [INFO.0] <2022-06-24; 16:25:36.333> Saving and writing settings to config file
   [INFO.0] <2022-06-24; 16:25:36.333> Successfully saved and wrote settings to config file
   [INFO.1] <2022-06-24; 16:25:36.333> Successfully initialized all subsystems
   [INFO.0] <2022-06-24; 16:25:42.328> Opening world background image dialog
   [INFO.0] <2022-06-24; 16:25:43.727> Selected world background image: /home/maplepy/Github/mc_player_tracker/worldImages/test.png
   [INFO.0] <2022-06-24; 16:25:43.735> Loading world background image took 12ms.
   Exception in thread "Thread-1" java.lang.IllegalArgumentException: invalid range properties
	at java.desktop/javax.swing.DefaultBoundedRangeModel.<init>(DefaultBoundedRangeModel.java:109)
	at java.desktop/javax.swing.JSlider.<init>(JSlider.java:293)
	at src.PlayerTrackerDecoder.lambda$LoadWorldImage$6(PlayerTrackerDecoder.java:325)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

There you go, sorry I forgot to give logs or anything :/ I was not expecting a reply tbh aha

**Comment by maplepy** [comment]
> Sorry about the wall of text, I try to be as descriptive as possible.

Oh yeah no worries, I prefer that over a one line sentence without much meaning :)

**Comment by AIP21** [comment]
Thanks for the logs! After checking them over I saw that there was an error creating the gui after loading the image. So it said that it loaded successfully but still froze up. It should be a simple fix, so I'll fix it and create a new release with the fix as soon as I get the chance.
I'll leave the issue open for now, but I'll close it if my fix resolves the issue.

**Comment by AIP21** [comment]
Ok, I just published a new release that should fix this bug. Let me know if it works!

**Comment by maplepy** [comment]
Alright seems like it fixed it :) Thanks

**Comment by maplepy** [comment]
By the way is there any plan on using the seed to generate the map image?

**Comment by AIP21** [comment]
Yes, I'm working on it and plan to release it soon. It's surprisingly more difficult that I expected it to be so it might take longer than I originally expected.
