### ISSUE TITLE
[Feature request] Get the map image with a seed?

### ISSUE THREAD

**Issue by maplepy** [AIP21/TrackerDecoderApp#3]

**Comment by AIP21** [comment]
Thanks for the idea! I've been planning on adding this in a future release, but I'll make sure to prioritize this and hopefully complete this soon. I'll mark this as closed once I finish this.

**Comment by maplepy** [comment]
Oh shoot didn't see you answered there, disregard the question in the other issue

That's great! I'm loving the app and the fast updates :)
